### PR TITLE
Keeping up to date

### PR DESCRIPTION
**Pull request by Konfuze**
Keeping up to date

### CODE REVIEW

**Comment by luixxiul** [comment]
This PR seems to break the commit history. cf: https://github.com/brave/browser-laptop/commit/699d4c277a162656c195fb9a32aa72a9b194a8b4#commitcomment-18128914 You don't have to create a PR to keep the forked repo updated.

**Comment by Konfuze** [comment]
@luixxiul Oops, sorry!

**Comment by luixxiul** [comment]
@Konfuze I'm not sure but deleting this repo and forking again should solve the issue for a moment.

FYI to update the repo this is a safer manner:
````
git remote add upstream https://github.com/brave/browser-laptop
git fetch upstream
git checkout master
git rebase upstream/master
git push origin master
````

**Comment by Konfuze** [comment]
@luixxiul okay, i'll delete it

**Pull request merged**
